/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Font;
import modelo.ConfigManager;
import util.ConstantesGUI;
import util.MetodosCompartidos;

/**
 *
 * @author Sergio Arturo
 */
public class CustomDLG extends javax.swing.JDialog {
    

    String mensaje;
    ConstantesGUI constante;
    
    private boolean confirmado = false;
    
    private final Font fuente = MetodosCompartidos.cargarFuente("/fonts/OpenSans-Bold.ttf", 20f);


    
    
    /**
     * Creates new form CustomDLG
     */
    public CustomDLG(java.awt.Frame parent, boolean modal, String mensaje, ConstantesGUI constante) {
        super(parent, modal);
        initComponents();
        
        this.mensaje = mensaje;
        this.constante = constante;
        
        
        cargarDiseno();
        
    }
    
    
    
    private void cargarDiseno(){
        MetodosCompartidos.cargarIcono(jblIcon, "/iconos/warning_ic.svg", 64, ConfigManager.getWarningColor());
        jblMensaje.setFont(fuente);
        jblMensaje.setForeground(ConfigManager.getTextColor());
        
        panelFondo.setBackground(ConfigManager.getBackgroundColor());
        
        
        btnConfirmar.setBackground(ConfigManager.getDeleteColor());
        btnCancelar.setBackground(ConfigManager.getBackgroundOptionColor());
        
        jblCancelar.setForeground(ConfigManager.getTextColor());
        jblConfirmar.setForeground(ConfigManager.getTextColor());
        
        this.setBackground(new Color(0, 0, 0, 0));

    
    }

    public boolean isConfirmado() {
        return confirmado;
    }
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new vista.CustomPanelRedondo();
        jblIcon = new javax.swing.JLabel();
        jblMensaje = new javax.swing.JLabel();
        btnConfirmar = new vista.CustomPanelRedondo();
        jblConfirmar = new javax.swing.JLabel();
        btnCancelar = new vista.CustomPanelRedondo();
        jblCancelar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(47, 47, 47));
        setMinimumSize(new java.awt.Dimension(400, 156));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 155));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 155));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        panelFondo.setBorderThickness(2.0F);
        panelFondo.setRoundBottomLeft(5);
        panelFondo.setRoundBottomRight(5);
        panelFondo.setRoundTopLeft(5);
        panelFondo.setRoundTopRight(5);
        panelFondo.setLayout(null);
        panelFondo.add(jblIcon);
        jblIcon.setBounds(20, 30, 80, 70);

        jblMensaje.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblMensaje.setText("<html>¿Estas seguro que quieres eliminar el Año? </html>");
        panelFondo.add(jblMensaje);
        jblMensaje.setBounds(110, 20, 270, 70);

        btnConfirmar.setRoundBottomLeft(5);
        btnConfirmar.setRoundBottomRight(5);
        btnConfirmar.setRoundTopLeft(5);
        btnConfirmar.setRoundTopRight(5);
        btnConfirmar.setLayout(null);

        jblConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jblConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblConfirmar.setText("Confirmar");
        jblConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblConfirmarMouseClicked(evt);
            }
        });
        btnConfirmar.add(jblConfirmar);
        jblConfirmar.setBounds(0, 0, 80, 30);

        panelFondo.add(btnConfirmar);
        btnConfirmar.setBounds(270, 100, 80, 30);

        btnCancelar.setRoundBottomLeft(5);
        btnCancelar.setRoundBottomRight(5);
        btnCancelar.setRoundTopLeft(5);
        btnCancelar.setRoundTopRight(5);
        btnCancelar.setLayout(null);

        jblCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jblCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblCancelar.setText("Cancelar");
        jblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblCancelarMouseClicked(evt);
            }
        });
        btnCancelar.add(jblCancelar);
        jblCancelar.setBounds(0, 0, 80, 30);

        panelFondo.add(btnCancelar);
        btnCancelar.setBounds(110, 100, 80, 30);

        getContentPane().add(panelFondo);
        panelFondo.setBounds(0, 0, 400, 155);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCancelarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jblCancelarMouseClicked

    private void jblConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblConfirmarMouseClicked
        // TODO add your handling code here:
        confirmado = true;
        this.dispose();
        
    }//GEN-LAST:event_jblConfirmarMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.CustomPanelRedondo btnCancelar;
    private vista.CustomPanelRedondo btnConfirmar;
    private javax.swing.JLabel jblCancelar;
    private javax.swing.JLabel jblConfirmar;
    private javax.swing.JLabel jblIcon;
    private javax.swing.JLabel jblMensaje;
    private vista.CustomPanelRedondo panelFondo;
    // End of variables declaration//GEN-END:variables
}
