/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;


import javax.swing.JLabel;
import vista.CustomPanelRedondo;

/**
 *
 * @author Sergio Arturo
 */
public class DesingJPanelAnio extends CustomPanelRedondo {
  

    /**
     * Creates new form JPanelAnio
     */
    public DesingJPanelAnio() {
        initComponents();
                
        setRoundBottomLeft(35);
        setRoundBottomRight(35);
        setRoundTopLeft(35);
        setRoundTopRight(35);
        
    }

    
    
    public JLabel getJblFechas() {
        return jblFechas;
    }

    public JLabel getJblNombreAnio2() {
        return jblNombreAnio2;
    }
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEncabezado = new vista.CustomPanelRedondo(35,35,0,0, true);
        jblFechas = new javax.swing.JLabel();
        jblNombreAnio2 = new javax.swing.JLabel();
        jbTactica = new javax.swing.JLabel();
        jPanelSeperador = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(455, 182));
        setRequestFocusEnabled(false);
        setLayout(null);

        jPanelEncabezado.setBackground(new java.awt.Color(52, 125, 210));
        jPanelEncabezado.setLayout(null);

        jblFechas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jblFechas.setForeground(new java.awt.Color(255, 255, 255));
        jblFechas.setText("Semana 1 - Dia 1");
        jPanelEncabezado.add(jblFechas);
        jblFechas.setBounds(30, 70, 330, 30);

        jblNombreAnio2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jblNombreAnio2.setForeground(new java.awt.Color(255, 255, 255));
        jblNombreAnio2.setText("Mejorar Habilidades sociales Ejemplo");
        jPanelEncabezado.add(jblNombreAnio2);
        jblNombreAnio2.setBounds(30, 25, 350, 30);

        add(jPanelEncabezado);
        jPanelEncabezado.setBounds(0, 0, 455, 110);

        jbTactica.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jbTactica.setText("Tácticas");
        add(jbTactica);
        jbTactica.setBounds(20, 130, 140, 27);

        jPanelSeperador.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanelSeperadorLayout = new javax.swing.GroupLayout(jPanelSeperador);
        jPanelSeperador.setLayout(jPanelSeperadorLayout);
        jPanelSeperadorLayout.setHorizontalGroup(
            jPanelSeperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanelSeperadorLayout.setVerticalGroup(
            jPanelSeperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        add(jPanelSeperador);
        jPanelSeperador.setBounds(120, 145, 310, 5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelEncabezado;
    private javax.swing.JPanel jPanelSeperador;
    private javax.swing.JLabel jbTactica;
    private javax.swing.JLabel jblFechas;
    private javax.swing.JLabel jblNombreAnio2;
    // End of variables declaration//GEN-END:variables
}
