/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import vista.CustomPanelRedondo;

/**
 *
 * @author Sergio Arturo
 */
public class DesingJPanelTacticaAnio extends CustomPanelRedondo {

    /**
     * Creates new form JPanelTacticaAnio
     */
    public DesingJPanelTacticaAnio() {
        initComponents();
        
        setRoundBottomLeft(15);
        setRoundBottomRight(15);
        setRoundTopLeft(15);
        setRoundTopRight(15);
    }
    
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); 
    
        int radius = 25;
        
        Graphics2D g2 = (Graphics2D) g.create();

        // 1. Activar suavizado
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // El grosor del borde es 1. Necesitamos un margen de 1 píxel.
        int margin = 1; 
        int width = getWidth();
        int height = getHeight();

        // 2. Dibujar el fondo redondeado (rellenado)
        g2.setColor(getBackground()); 
        // Dibujamos el fondo ligeramente más pequeño para dejar espacio al borde
        g2.fillRoundRect(
            margin, margin,          // X e Y iniciales
            width - margin * 2,      // Ancho ajustado
            height - margin * 2,     // Alto ajustado
            radius, radius
        );

        // 3. Dibujar el borde redondeado (contorno)
        g2.setColor(Color.GRAY);
        g2.setStroke(new BasicStroke(1)); 
        // Dibujamos el contorno justo donde termina el fondo relleno
        g2.drawRoundRect(
            margin, margin,          // X e Y iniciales
            width - margin * 2,      // Ancho ajustado
            height - margin * 2,     // Alto ajustado
            radius, radius
        ); 

        g2.dispose();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblNombreTactica = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(52, 125, 210));
        setPreferredSize(new java.awt.Dimension(460, 60));
        setLayout(null);

        jblNombreTactica.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblNombreTactica.setForeground(new java.awt.Color(255, 255, 255));
        jblNombreTactica.setText("Leer 5 min");
        add(jblNombreTactica);
        jblNombreTactica.setBounds(30, 16, 150, 30);
        add(jPanel1);
        jPanel1.setBounds(330, 5, 50, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblNombreTactica;
    // End of variables declaration//GEN-END:variables
}
