/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import vista.DesingJPanelAnio;
import vista.DesingJPanelTacticaAnio;
import java.awt.Dimension;

/**
 *
 * @author Sergio Arturo
 */
public class ViewJPanelSeccioAnio extends javax.swing.JPanel {
    
    
    Dimension dimension;
    

    /**
     * Creates new form JPanelSeccioAnio
     */
    public ViewJPanelSeccioAnio() {
        initComponents();
        
        jScrollPaneAnio.setOpaque(false);
        jScrollPaneAnio.getViewport().setOpaque(false);
        jScrollPaneAnio.setBorder(null); // Quita el borde cuadrado exterior del scroll
      //  jPanelContenedorAnio.setOpaque(false);
        
        
        pruebas();
        
    }
    
    
    private void pruebas(){


        
        int ancho = 76;
        
        DesingJPanelAnio anio = new DesingJPanelAnio();
        anio.setBounds(27, -109, 455, 182);
        
        
        for (int i = 0; i < 10; i++){
            
            DesingJPanelTacticaAnio panelTactica = new DesingJPanelTacticaAnio();
            panelTactica.setBounds(20, 170 + (i * ancho), 410, 60);
            
            anio.setBounds(27, -109, 455, 250 + (i * ancho));
            
            anio.add(panelTactica);
        }
        
        jPanelListaAnio.setPreferredSize(new Dimension(510, ancho + (ancho * 10)));
        
        
        
//        
//        
        
//        
//        anio.setBounds(0, 0, 455, 240);
//        
//        anio.revalidate();
//        anio.repaint();
        
        jPanelListaAnio.add(anio);
        
        
        
       // anio.setBounds(0, 0, jPanelListaAnio.getWidth(), 182);
        
        
        jPanelListaAnio.revalidate();
        jPanelListaAnio.repaint();
        
        int alturaProducto = 80; 
    
//        for(int i = 0; i < 1; i++){
//            
//            JPanelAnio anio = new JPanelAnio();
//            
//            anio.setBounds(20, 200, 400, 60);
//            
//            
//            jPanelAnioTacticas.add(anio);
//            
//            
//            int numeroExtras = 1;
//             
//             if(numeroExtras > 0){
//                 int nuevaAltura = alturaProducto * numeroExtras;
//                 
//                 if(dimension == null){
//                     dimension = new Dimension();
//                 }
//                 
//                 int anchoActual = jPanelAnioTacticas.getPreferredSize().width;
//                 
//                 dimension.setSize(anchoActual, nuevaAltura);
//                 jPanelAnioTacticas.setPreferredSize(dimension);
//                 
//             }
//             
//             else{
//                 jPanelAnioTacticas.setPreferredSize(new Dimension(jPanelAnioTacticas.getPreferredSize().width,10));
//             }
//
//                
//            }
//            
//            
//            
//            
//        
//        
//        jPanelAnioTacticas.revalidate();
//        jPanelAnioTacticas.repaint();
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblInicio1 = new javax.swing.JLabel();
        jScrollPaneAnio = new javax.swing.JScrollPane();
        jPanelListaAnio = new javax.swing.JPanel();
        jPanelAnio1 = new vista.DesingJPanelAnio();

        setBackground(new java.awt.Color(47, 47, 47));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 67, 67)));
        setPreferredSize(new java.awt.Dimension(527, 613));
        setLayout(null);

        jblInicio1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblInicio1.setForeground(new java.awt.Color(255, 255, 255));
        jblInicio1.setText("Año de 12 Semanas");
        add(jblInicio1);
        jblInicio1.setBounds(60, 20, 220, 30);

        jScrollPaneAnio.setBackground(new java.awt.Color(47, 47, 47));
        jScrollPaneAnio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPaneAnio.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneAnio.setPreferredSize(new java.awt.Dimension(300, 100));

        jPanelListaAnio.setBackground(new java.awt.Color(47, 47, 47));
        jPanelListaAnio.setForeground(new java.awt.Color(47, 47, 47));
        jPanelListaAnio.setPreferredSize(new java.awt.Dimension(455, 10));
        jPanelListaAnio.setLayout(null);
        jScrollPaneAnio.setViewportView(jPanelListaAnio);

        add(jScrollPaneAnio);
        jScrollPaneAnio.setBounds(10, 168, 510, 430);
        add(jPanelAnio1);
        jPanelAnio1.setBounds(37, 60, 455, 182);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.DesingJPanelAnio jPanelAnio1;
    private javax.swing.JPanel jPanelListaAnio;
    private javax.swing.JScrollPane jScrollPaneAnio;
    private javax.swing.JLabel jblInicio1;
    // End of variables declaration//GEN-END:variables
}
